#!/bin/bash

# App deployed as debug right now!

# Initialize git
#git init
#heroku git:remote -a zozor-remindme

# Generate requirements.txt 
source venv/bin/activate
pip freeze > requirements.txt

# Generate js bundle
node_modules/browserify/bin/cmd.js -e front/main.coffee -o app/static/javascripts/bundle.js --verbose -t coffeeify

# Run
git push -f heroku master && heroku ps:scale web=1

# Switch to logs
heroku logs -t
